# travis config, based on https://github.com/craigcitro/r-travis

language: c

env:
   global:
     - _R_CHECK_TIMINGS_=0

branches:
  only:
   - master

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh aptget_install r-cran-rjava
  - sudo R CMD javareconf
  - ./travis-tool.sh github_package berndbischl/BBmisc
  - ./travis-tool.sh github_package berndbischl/parallelMap
  - ./travis-tool.sh github_package berndbischl/ParamHelpers
  - ./travis-tool.sh install_deps
  - java -cp /usr/local/lib/R/site-library/RWekajars/java/weka.jar weka.core.WekaPackageManager -install-package thirdparty/XMeans1.0.4.zip


script: travis_wait ./travis-tool.sh run_tests

after_script:
  - ./travis-tool.sh dump_logs


notifications:
  email:
    recipients:
        - bernd_bischl@gmx.net
        - michellang@gmail.com
        - travis.mlr@jakob-r.de
        - lars.kotthoff@insight-centre.org
        - schiffner@math.uni-duesseldorf.de
        - erich.studerus@gmail.com
    on_success: change
    on_failure: always
